import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import '../styles/AIDocumentForm.css';

// Default form fields
const DEFAULT_FIELD_KEYS = [
  'Experiment Name',
  'Compiler Name',
  'Experiment No',
  'Date',
  'Aim of the Program',
  'Program',
  'Output',
];

export default function AIDocumentForm({ details, onSuccess }) {
  const navigate = useNavigate();
  // Use details prop for keys and values, fallback to default keys if not provided
  const formKeys = details && Object.keys(details).length > 0 ? Object.keys(details) : DEFAULT_FIELD_KEYS;

  const [formData, setFormData] = useState(() => {
    const initial = {};
    (details && Object.keys(details).length > 0 ? Object.keys(details) : DEFAULT_FIELD_KEYS).forEach(key => {
      initial[key] = (details && details[key] !== undefined) ? details[key] : '';
    });
    return initial;
  });

  const [isSubmitting, setIsSubmitting] = useState(false);

  // Update formData when details prop changes
  useEffect(() => {
    const initial = {};
    (details && Object.keys(details).length > 0 ? Object.keys(details) : DEFAULT_FIELD_KEYS).forEach(key => {
      initial[key] = (details && details[key] !== undefined) ? details[key] : '';
    });
    setFormData(initial);
  }, [details]);

  const handleChange = (key, value) => {
    setFormData(prev => ({ ...prev, [key]: value }));
  };


  // Handle image upload for Output field
  const handleImageChange = (key, file) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onloadend = () => {
      setFormData(prev => ({ ...prev, [key]: reader.result }));
    };
    reader.readAsDataURL(file);
  };

  // AI Generate for Program
  const [isAIGenerating, setIsAIGenerating] = useState(false);
  const [isAIGeneratingImage, setIsAIGeneratingImage] = useState(false);

  const handleAIGenerateProgram = async () => {
    // Combine all field values into a single string for the AI
    const aim = Object.entries(formData)
      .filter(([k, v]) => typeof v === 'string' && v.trim() !== '')
      .map(([k, v]) => `${k}: ${v}`)
      .join('\n');
    if (!aim) {
      toast.error('Please fill in the form fields first.');
      return;
    }
    setIsAIGenerating(true);
    try {
      const response = await fetch('http://localhost:8000/ai-code-generation/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ program_aim: aim }),
      });
      const data = await response.json();
      if (data?.result === 'success' && data?.code) {
        setFormData(prev => ({ ...prev, Program: data.code }));
        toast.success('Code generated by AI!');
      } else {
        toast.error('AI code generation failed.');
      }
    } catch (e) {
      toast.error('AI code generation failed.');
    } finally {
      setIsAIGenerating(false);
    }
  };

  // AI Generate for Output (image)
  const handleAIGenerateOutput = async () => {
    // Combine all field values into a single string for the AI
    const aim = Object.entries(formData)
      .filter(([k, v]) => typeof v === 'string' && v.trim() !== '')
      .map(([k, v]) => `${k}: ${v}`)
      .join('\n');
    if (!aim) {
      toast.error('Please fill in the form fields first.');
      return;
    }
    setIsAIGeneratingImage(true);
    try {
      const response = await fetch('http://localhost:8000/ai-image-generation/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ program_aim: aim }),
      });
      if (response.ok && response.headers.get('content-type')?.includes('image/')) {
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        setFormData(prev => ({ ...prev, Output: url }));
        toast.success('Image generated by AI!');
      } else {
        toast.error('AI image generation failed.');
      }
    } catch (e) {
      toast.error('AI image generation failed.');
    } finally {
      setIsAIGeneratingImage(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);
    try {
      const response = await fetch('http://localhost:8000/final-submission', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
      if (response.ok && response.headers.get('content-type')?.includes('application/vnd.openxmlformats-officedocument.wordprocessingml.document')) {
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'Sample_template.docx';
        document.body.appendChild(a);
        a.click();
        a.remove();
        window.URL.revokeObjectURL(url);
        toast.success('Final submission successful!');
        setTimeout(() => navigate('/home'), 1000);
        onSuccess?.();
      } else {
        toast.error('Submission failed.');
      }
    } catch (error) {
      toast.error('An error occurred during submission.');
      console.error('Submission error:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="form-container" style={{
      height: '100vh',
      width: '100vw',
      overflow: 'auto',
      position: 'relative',
    }}>
      {isSubmitting && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100vw',
          height: '100vh',
          background: 'rgba(255,255,255,0.7)',
          zIndex: 9999,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
        }}>
          <div className="loading-spinner" style={{
            width: 60,
            height: 60,
            border: '6px solid #e0e0e0',
            borderTop: '6px solid #6366f1',
            borderRadius: '50%',
            animation: 'spin 1s linear infinite',
            marginBottom: 24,
          }} />
          <div style={{ fontSize: 22, fontWeight: 600, color: '#333' }}>Agent taking action...</div>
          <style>{`
            @keyframes spin {
              0% { transform: rotate(0deg); }
              100% { transform: rotate(360deg); }
            }
          `}</style>
        </div>
      )}
      {/* Animated background elements */}
      <div className="background-elements">
        <div className="background-inner">
          <div className="floating-element floating-element-1"></div>
          <div className="floating-element floating-element-2"></div>
          <div className="floating-element floating-element-3"></div>
        </div>
      </div>

      <div className="form-card" style={{ marginTop: '400px' }}>
        <div className="form-card-inner">
          <div className="form-header">
            <h2 className="form-title">
              AI needs this much of documents to fill the template
            </h2>
            <p className="form-subtitle">
              Provide the required information to generate your document
            </p>
          </div>

          <form onSubmit={handleSubmit} className="document-form">
            {formKeys.map((key, idx) => {
              if (key.toLowerCase() === 'program') {
                return (
                  <React.Fragment key={key}>
                    <div className="form-group">
                      <label htmlFor={key} className="form-label">
                        {key}
                      </label>
                      <textarea
                        id={key}
                        value={formData[key] || ''}
                        onChange={(e) => handleChange(key, e.target.value)}
                        placeholder={`Enter ${key.toLowerCase()}`}
                        className="form-input"
                        required
                        rows={6}
                      />
                    </div>
                    <div style={{ width: '100%', display: 'flex', justifyContent: 'flex-end', marginBottom: 16 }}>
                      <button
                        type="button"
                        className="ai-generate-btn"
                        style={{
                          background: '#6366f1', color: '#fff', border: 'none', borderRadius: 8, padding: '10px 20px', fontWeight: 600, cursor: isAIGenerating ? 'not-allowed' : 'pointer', fontSize: '1rem', boxShadow: '0 2px 8px #e0e7ef', transition: 'background 0.2s',
                        }}
                        onClick={handleAIGenerateProgram}
                        disabled={isAIGenerating}
                      >
                        {isAIGenerating ? (
                          <>
                            <span className="loading-spinner" style={{
                              width: 18, height: 18, border: '3px solid #e0e0e0', borderTop: '3px solid #fff', borderRadius: '50%', display: 'inline-block', marginRight: 8, animation: 'spin 1s linear infinite', verticalAlign: 'middle'
                            }} />
                            Generating...
                          </>
                        ) : (
                          'AI Generate'
                        )}
                      </button>
                    </div>
                    {/* Output field comes after Program */}
                    {formKeys.find(k => k.toLowerCase() === 'output') && (
                      <>
                        <div className="form-group" key="output-upload">
                          <label htmlFor="Output" className="form-label">Output</label>
                          <input
                            id="Output"
                            type="file"
                            accept="image/*"
                            onChange={e => {
                              const file = e.target.files && e.target.files[0];
                              handleImageChange('Output', file);
                            }}
                            className="form-input"
                            required
                          />
                          {formData['Output'] && (formData['Output'].startsWith('data:image') || formData['Output'].startsWith('blob:')) && (
                            <>
                              <img src={formData['Output']} alt="Preview" style={{ marginTop: 8, maxWidth: 200, maxHeight: 120, borderRadius: 8 }} />
                              <div style={{ marginTop: 8 }}>
                                <a
                                  href={formData['Output']}
                                  download={
                                    formData['Output'].startsWith('data:image') ? 'output-image.png' : 'output-image.png'
                                  }
                                  style={{
                                    display: 'inline-block',
                                    background: '#6366f1',
                                    color: '#fff',
                                    border: 'none',
                                    borderRadius: 8,
                                    padding: '6px 16px',
                                    fontWeight: 600,
                                    fontSize: '0.95rem',
                                    textDecoration: 'none',
                                    marginTop: 4,
                                    boxShadow: '0 2px 8px #e0e7ef',
                                    transition: 'background 0.2s',
                                  }}
                                >
                                  Download Image
                                </a>
                              </div>
                            </>
                          )}
                        </div>
                        <div style={{ width: '100%', display: 'flex', justifyContent: 'flex-end', marginBottom: 16 }}>
                          <button
                            type="button"
                            className="ai-generate-btn"
                            style={{
                              background: '#6366f1', color: '#fff', border: 'none', borderRadius: 8, padding: '10px 20px', fontWeight: 600, cursor: isAIGeneratingImage ? 'not-allowed' : 'pointer', fontSize: '1rem', boxShadow: '0 2px 8px #e0e7ef', transition: 'background 0.2s',
                            }}
                            onClick={handleAIGenerateOutput}
                            disabled={isAIGeneratingImage}
                          >
                            {isAIGeneratingImage ? (
                              <>
                                <span className="loading-spinner" style={{
                                  width: 18, height: 18, border: '3px solid #e0e0e0', borderTop: '3px solid #fff', borderRadius: '50%', display: 'inline-block', marginRight: 8, animation: 'spin 1s linear infinite', verticalAlign: 'middle'
                                }} />
                                Generating...
                              </>
                            ) : (
                              'AI Generate'
                            )}
                          </button>
                        </div>
                      </>
                    )}
                  </React.Fragment>
                );
              }
              if (key.toLowerCase() === 'output') {
                // Output field is already rendered after Program
                return null;
              }
              return (
                <div key={key} className="form-group">
                  <label htmlFor={key} className="form-label">
                    {key}
                  </label>
                  <input
                    id={key}
                    type="text"
                    value={formData[key] || ''}
                    onChange={(e) => handleChange(key, e.target.value)}
                    placeholder={`Enter ${key.toLowerCase()}`}
                    className="form-input"
                    required
                  />
                </div>
              );
            })}

            <button
              type="submit"
              disabled={isSubmitting}
              className="submit-button"
            >
              {isSubmitting ? (
                <>
                  <div className="loading-spinner"></div>
                  AI Taking Actions...
                </>
              ) : (
                <>
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <line x1="22" y1="2" x2="11" y2="13"></line>
                    <polygon points="22,2 15,22 11,13 2,9"></polygon>
                  </svg>
                  Submit
                </>
              )}
            </button>
          </form>
        </div>
      </div>

      <ToastContainer 
        position="top-right" 
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="colored"
        className="toast-container"
      />
    </div>
  );
}